theme: lewismiddleton/cayman-dark
title: Mr. Infinity
image: https://raw.githubusercontent.com/Mr-Infinity-Bot/bucket/main/assets/infinitybucket.png
description: Bot for Anti Raid, Anti Alts, Verification and more!
